[package]
name = "pam_viewer"
version = "0.1.0"
authors = ["y1z <whyis2cool@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# sdl2 crate : https://crates.io/crates/sdl2
sdl2 = "0.34.5"